[package]
name = "libnesmulator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
nesfile = { path = "../nesfile" }
bitvec = "1.0"
log = "0.4.22"
nom = { workspace = true }

[lints]
workspace = true
